// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(KodlamaioDbContext))]
    [Migration("20220911104136_Add_Feature_ProgramingTechnology")]
    partial class Add_Feature_ProgramingTechnology
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.ProgramingLangues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ProgramingLangues", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProgramingTechnologies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Name");

                    b.Property<int>("ProgLanguageId")
                        .HasColumnType("int")
                        .HasColumnName("ProgLanguageId");

                    b.Property<int?>("ProgramingLanguesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramingLanguesId");

                    b.ToTable("ProgramingTechnologies", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProgramingTechnologies", b =>
                {
                    b.HasOne("Domain.Entities.ProgramingLangues", "ProgramingLangues")
                        .WithMany("ProgramingTechnologies")
                        .HasForeignKey("ProgramingLanguesId");

                    b.Navigation("ProgramingLangues");
                });

            modelBuilder.Entity("Domain.Entities.ProgramingLangues", b =>
                {
                    b.Navigation("ProgramingTechnologies");
                });
#pragma warning restore 612, 618
        }
    }
}
